SRCS := ./pll.v \
        ./soc_fpga_top.v \
        ../../src/cache.v \
        ../../src/cache_sram_D$$.v \
        ../../src/cache_sram_I$$.v \
        ../../src/clint.v \
        ../../src/dcache.v \
        ../../src/fifo.v \
        ../../src/gf180mcu_fd_ip_sram__sram512x8m8wm1_wrapper.v \
        ../../src/gpio.v \
        ../../src/icache.v \
        ../../src/kianv_harris_edition/alu.v \
        ../../src/kianv_harris_edition/alu_decoder.v \
        ../../src/kianv_harris_edition/associative_cache.v \
        ../../src/kianv_harris_edition/control_unit.v  \
        ../../src/kianv_harris_edition/csr_decoder.v \
        ../../src/kianv_harris_edition/csr_exception_handler.v \
        ../../src/kianv_harris_edition/csr_unit.v \
        ../../src/kianv_harris_edition/datapath_unit.v \
        ../../src/kianv_harris_edition/design_elements.v \
        ../../src/kianv_harris_edition/design_elements_fpgacpu_ca.v \
        ../../src/kianv_harris_edition/divider.v \
        ../../src/kianv_harris_edition/divider_decoder.v \
        ../../src/kianv_harris_edition/extend.v \
        ../../src/kianv_harris_edition/interrupt_controller.v \
        ../../src/kianv_harris_edition/kianv_harris_mc_edition.v \
        ../../src/kianv_harris_edition/load_alignment.v \
        ../../src/kianv_harris_edition/load_decoder.v \
        ../../src/kianv_harris_edition/main_fsm.v \
        ../../src/kianv_harris_edition/multiplier.v \
        ../../src/kianv_harris_edition/multiplier_decoder.v \
        ../../src/kianv_harris_edition/multiplier_extension_decoder.v \
        ../../src/kianv_harris_edition/register_file.v \
        ../../src/kianv_harris_edition/store_alignment.v \
        ../../src/kianv_harris_edition/store_decoder.v \
        ../../src/kianv_harris_edition/sv32.v \
        ../../src/kianv_harris_edition/sv32_table_walk.v \
        ../../src/kianv_harris_edition/sv32_translate_data_to_physical.v \
        ../../src/kianv_harris_edition/sv32_translate_instruction_to_physical.v \
        ../../src/plic.v \
        ../../src/rx_uart.v \
        ../../src/sdram/mt48lc16m16a2_ctrl.v \
        ../../src/soc.v \
        ../../src/spi.v \
        ../../src/spi_nor_flash.v \
        ../../src/sram_sp.v \
        ../../src/sram_sp_gf180_512x56.v \
        ../../src/tx_uart.v
